version: '3'
services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    command: python /code/Capstone/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
#  nginx:
#    restart: always
#    build: ./nginx/
#    depends_on:
#      - web
#    ports:
#      - "80:80"
##      - "443:443"
